// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCto29qpbtzbZccUhYityQYjvJqB1LqKDo',
    appId: '1:18021494196:web:e9028f25af80f2c49696e1',
    messagingSenderId: '18021494196',
    projectId: 'lapor-book-64bd3',
    authDomain: 'lapor-book-64bd3.firebaseapp.com',
    storageBucket: 'lapor-book-64bd3.appspot.com',
    measurementId: 'G-2GTYYV1KR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcIvo6-7d-dFRIdoGnDRaK9eN1gBxYcUw',
    appId: '1:18021494196:android:55bdf6476bf4c0e29696e1',
    messagingSenderId: '18021494196',
    projectId: 'lapor-book-64bd3',
    storageBucket: 'lapor-book-64bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLAomd3mgy8HAG-9eAijX2_-GfWV5oOZg',
    appId: '1:18021494196:ios:23546a51d638deaf9696e1',
    messagingSenderId: '18021494196',
    projectId: 'lapor-book-64bd3',
    storageBucket: 'lapor-book-64bd3.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
